# Generated by Django 4.0.3 on 2022-04-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_images'),
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, related_name='comment_project', to='project.project', verbose_name='댓글이 속한 프로젝트'),
            preserve_default=False,
        ),
    ]
