# Generated by Django 4.0.1 on 2022-01-25 16:52

import apps.core.utility
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('core', '0001_initial'),
        ('user', '0002_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default=apps.core.utility.generate_random_string, max_length=20, unique=True, verbose_name='프로필 Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='skill.Skill', verbose_name='기술 목록'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='사용자 이미지'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('source', models.URLField(max_length=120, verbose_name='링크 URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_user', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '링크',
                'db_table': 'link',
            },
        ),
    ]
