# Generated by Django 4.0.1 on 2022-01-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('core', '0001_initial'),
        ('user', '0002_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default='u0r9yunp19hki1l', max_length=20, unique=True, verbose_name='프로필 Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='skill.Skill', verbose_name='기술 목록'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='사용자 이미지'),
        ),
    ]
