# Generated by Django 4.0.1 on 2022-03-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_expected_salary_user_hobby_otherexperience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Functions',
            new_name='DevelopedFunction',
        ),
    ]
