# Generated by Django 4.0.1 on 2022-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('user', '0003_rename_functions_developedfunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='tag.Position', verbose_name='포지션'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='tag.Tech', verbose_name='기술 목록'),
        ),
    ]
