# Generated by Django 4.0.1 on 2022-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_position'),
        ('user', '0003_user_slug_alter_user_introduction_alter_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='users', to='skill.Position', verbose_name='포지션'),
        ),
    ]
