# Generated by Django 4.0.1 on 2022-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_positions_alter_user_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='otherexperience',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='otherexperience',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
