# Generated by Django 4.0.1 on 2022-01-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '게시글'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='post_liker', to=settings.AUTH_USER_MODEL, verbose_name='좋아요누른사람'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='썸네일이미지'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성된 날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 날짜'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
