# Generated by Django 4.0.1 on 2022-01-31 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='post_liker', to=settings.AUTH_USER_MODEL, verbose_name='좋아요누른사람'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='썸네일이미지'),
        ),
    ]
