# Generated by Django 4.0.1 on 2022-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_remove_post_likes_post_liker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='author',
        ),
    ]
