# Generated by Django 4.0.1 on 2022-01-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('title', models.CharField(max_length=40, verbose_name='프로젝트 제목')),
                ('content', models.TextField(verbose_name='프로젝트 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL, verbose_name='프로젝트 작성자')),
                ('liker', models.ManyToManyField(related_name='project_liker', to=settings.AUTH_USER_MODEL, verbose_name='프로젝트에 좋아요 남긴 사용자들')),
                ('thumbnail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='프로젝트 썸네일')),
            ],
            options={
                'verbose_name_plural': '프로젝트',
                'db_table': 'project',
            },
        ),
    ]
