# Generated by Django 4.0.1 on 2022-01-23 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liker',
            field=models.ManyToManyField(related_name='project_liker', to=settings.AUTH_USER_MODEL, verbose_name='프로젝트에 좋아요 남긴 사용자들'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
