# Generated by Django 4.0.1 on 2022-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='project_tech_stack', to='tag.Tech', verbose_name='기술 목록'),
        ),
    ]
