# Generated by Django 4.0.1 on 2022-01-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_liker_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '프로젝트'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
