# Generated by Django 4.0.1 on 2022-01-31 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('tag', '0001_initial'),
        ('project', '0003_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='liker',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_liker', to=settings.AUTH_USER_MODEL, verbose_name='프로젝트에 좋아요 남긴 사용자들'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_tech_stack', to='tag.Tech', verbose_name='기술 목록'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='프로젝트 썸네일'),
        ),
    ]
