# Generated by Django 4.0.1 on 2022-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_liker_alter_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.TextField(blank=True, null=True, verbose_name='어려웠던 점'),
        ),
        migrations.AddField(
            model_name='project',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.TextField(blank=True, null=True, verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AddField(
            model_name='project',
            name='takeaway',
            field=models.TextField(blank=True, null=True, verbose_name='배운 점'),
        ),
    ]
