# Generated by Django 4.0.1 on 2022-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('project', '0005_project_difficulty_project_ended_at_project_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_tech', to='tag.Tech', verbose_name='기술 목록'),
        ),
    ]
