# Generated by Django 4.0.1 on 2022-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_tech_stack_project_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
