# Generated by Django 4.0.1 on 2022-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='기술')),
            ],
            options={
                'verbose_name_plural': '기술',
                'db_table': 'skill',
            },
        ),
    ]
