# Generated by Django 4.0.4 on 2022-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='포지션')),
            ],
            options={
                'verbose_name_plural': '포지션',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='기술')),
            ],
            options={
                'verbose_name_plural': '기술',
                'db_table': 'tech',
            },
        ),
    ]
